id: P4B236351
initial_creation_type: ocr
source_metadata:
  volumes:
    d5af616d6ff24e2a9792472ece959eee:
      base_file: v105.txt
      image_group_id: I1PD95950
      title: རིགས་པའི་ཐིགས་པའི་དོན་བསྡུས་པ།
      total_pages: 910
      volume_number: 105
